name: lib_flutter_token
description: Library for Flutter applications to encode/decode Diagro tokens
version: 1.0.1
homepage: https://www.diagro.be
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.1"

dependencies:
  dart_jsonwebtoken: ^2.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.19.3
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter: